[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "Pathorchestra"
version = "1.0.0"
description = "Integrated Biomedical Platform for AI-assisted Healthcare"

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.24.1"
flask = "^3.1.0"
pytorch = "^1.9"
pandas = "^2.0"
numpy = "^1.25.1"
matplotlib = "^3.8.0"
plotly = "^5.17.0"

[tool.poetry.dev-dependencies]
